' Simbol Class — Multiplisitas (1, 0..*). UML 2.5.1.
@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Segoe UI"
skinparam classAttributeIconSize 0
hide circle
class A
class B
A "1" -- "0..*" B
@enduml
